config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    collection do
      get :search
    end
    member do
      get :rate_new
    end
  end
  resources :rates
  resources :drivers do
    member do
      get :auto_new
    end
  end
  resources :autos
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  
  attr_accessor :remove_rate
  attr_accessor :remove_rate_id
  
  after_update :destroy_rate
  
  belongs_to :driver
  belongs_to :rate, inverse_of: :orders
	accepts_nested_attributes_for :rate, allow_destroy: true
  
	validates :date, presence: true
	validates :time, presence: true
	validates :from_adress, presence: true, length: { maximum: 512 }
	validates :to_adress, presence: true, length: { maximum: 512 }
	validates :passangers_count, numericality: { only_integer: true, allow_nil: false }
	validates :lenght_of_the_route, numericality: { allow_nil: false }
	validates :driver, presence: true
	validates :rate, presence: true
  
  
  
  protected
  
  def destroy_rate
    if (remove_rate == "true")
      relationship = Rate.find(remove_rate_id).orders.select{|s| s.id != self.id}
      if (relationship.empty? and (rate_id.to_i != remove_rate_id.to_i))
        Rate.delete(remove_rate_id)
      end  
    end
  end
  
  def self.search(params)
    result = Order.includes(:rate, driver: [:auto]).references(:rate, driver: [:auto])
    # BYORDER
    if params['time_from'].present?
      result = result.where.not(time: Time.at(0)...Time.parse(("2000-01-01" + " " + params['time_from'] + " " + "UTC")))
    end
    if params['time_to'].present?
      result = result.where(time: Time.at(0)..Time.parse(("2000-01-01" + " " + params['time_to'] + " " + "UTC")))
    end
    if params['from_address'].present?
      result = result.where(departure_address: params['from_address'])
    end
    if params['to_address'].present?
      result = result.where(arrival_address: params['to_address'])
    end
    if params['passengers_count'].present?
      result = result.where(passengers_count: params['passengers_count'])
    end
    if params['length_of_the_route'].present?
      tmp = params['length_of_route'].split(/\D+/)
      result = result.where(length_of_the_route: (tmp[0].to_f..tmp[0].to_f))
    end
    if params['date_from'].present?
      result = result.where.not(date: Date.new(0)...Date.parse(params['date_from']))
    end
    if params['date_to'].present?
      result = result.where(date: Date.new(0)..Date.parse(params['date_to']))
    end

    # BYRATE
    if params['rate_name'].present?
      result = result.where(rates: {name: params['rate_name']})
    end
    if params['times_of_day'].present?
      result = result.where(rates: {times_of_day: params['times_of_day']})
    end
    if params['how_far'].present?
      result = result.where(rates: {how_far: params['how_far']})
    end
    if params['PPK'].present?
      tmp = params['PPK'].split(/\D+/)
      result = result.where(rates: {PPK: (tmp[0].to_f..tmp[1].to_f)}  )
    end

    # BYAUTO
    if params['auto_model'].present?
      result = result.where(autos: {model: params['auto_model']})
    end
    if params['auto_type'].present?
      result = result.where(autos: {myclass: params['auto_class']})
    end
    if params['state_number'].present?
      result = result.where(autos: {number: params['number']})
    end
    if params['color'].present?
      result = result.where(autos: {color: params['color']})
    end
    if params['release'].present?
      result = result.where(autos: {year: params['year']})
    end

    # BYDRIVER
    if params['driver_fn'].present?
      result = result.where(drivers: {fn: params['driver_fn']})
    end
    if params['driver_sn'].present?
      result = result.where(drivers: {sn: params['driver_sn']})
    end
    if params['driver_ln'].present?
      result = result.where(drivers: {ln: params['driver_ln']})
    end
    if params['driver_birthdate'].present?
      result = result.where(drivers: {birthdate: params['driver_birthdate']})
    end
    if params['driver_TIN'].present?
      result = result.where(drivers: {TIN: params['driver_TIN']})
    end
    if params['driver_passport'].present?
      result = result.where(drivers: {passport: params['driver_passport']})
    end

    result.all
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action -> {check_permissions('admin', 'operator')}, except: [:show, :index]

  # GET /orders
  # GET /orders.json
  
  def search
    if params.has_key?('search')
      @orders = Order.search(params['search'])
    else
      @orders = []
    end
    params['search'] ||= {}
    @s_rate_name = params.has_key?('search') ? params[:search][:rate_name] : ""
    @s_rate_time_of_day = params.has_key?('search') ? params[:search][:times_of_day] : ""
    @s_rate_how_far = params.has_key?('search') ? params[:search][:rate_how_far] : ""
    @s_auto_model = params.has_key?('search') ? params[:search][:auto_model] : ""
    @s_auto_class = params.has_key?('search') ? params[:search][:auto_class] : ""
    @s_auto_color = params.has_key?('search') ? params[:search][:auto_color] : ""
  end
  
  def rate_new
    respond_to do |format|
      format.js do
        @order = Order.find(params[:id])
        @order.rate = Rate.new
      end
    end
  end
  
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: t('app.orders.create.success') }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: t('app.orders.update.success') }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    message = @order.destroy ? t('app.orders.destroy.success') : "#{@order.errors[:base].first.to_s}"
    respond_to do |format|
      format.html { redirect_to orders_url, notice: message }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:date, :time, :from_adress, :to_adress, :passangers_count, :lenght_of_the_route, :driver_id, :rate_id,:remove_rate, :remove_rate_id,
        rate_attributes: [:id, :name, :times_of_day, :how_far, :PPK]
        )
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_for @order do |f|
  - if @order.errors.any? && @current_role_user.is_admin?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |msg|
          %li= msg
          
  .row
    .col-md-6
      .form-group
        .row
          .col-md-4
            = f.label :date
          .col-md-8
            .input-group.date.datepicker
              = f.text_field :date, value: lnil(f.object.date), class: 'form-control'
              %span.input-group-addon
                %span.glyphicon.glyphicon-calendar
      = f.error_messages_for(:date, class: "bg-danger")
      .form-group
        .row
          .col-md-4
            = f.label :time
          .col-md-8
            .input-group.date.timepicker
              = f.text_field :time, class: 'form-control'
              %span.input-group-addon
                %span.glyphicon.glyphicon-time
      = f.error_messages_for(:time, class: "bg-danger")
      .form-group
        .row
          .col-md-4
            = f.label :from_adress
          .col-md-8
            = f.text_field :from_adress, class: 'form-control'
      = f.error_messages_for(:from_adress, class: "bg-danger")
      .form-group
        .row
          .col-md-4
            = f.label :to_adress
          .col-md-8
            = f.text_field :to_adress, class: 'form-control'
      = f.error_messages_for(:to_adress, class: "bg-danger")
      .form-group
        .row
          .col-md-4 
            = f.label :passangers_count
          .col-md-8
            = f.text_field :passangers_count, class: 'form-control'
      = f.error_messages_for(:passangers_count, class: "bg-danger")
      .form-group
        .row
          .col-md-4
            = f.label :lenght_of_the_route
          .col-md-8
            = f.text_field :lenght_of_the_route, class: 'form-control'
      = f.error_messages_for(:lenght_of_the_route, class: "bg-danger")
      .form-group
        .row
          .col-md-4
            = f.label :driver
          .col-md-8
            = select(:order, :driver_id, Driver.all.collect {|p| [ (p.fn + ' ' + p.sn + ' ' + p.ln), p.id ] }, { include_blank: true }, :data => {'style' => "btn-primary"}, :class => 'form-control')
      = f.error_messages_for(:driver, class: "bg-danger" )
    - if @current_role_user.present? and @current_role_user.is_admin?
      .col-md-6
        = render('rate_form', f: f)
  .col-md-6.col-md-offset-3
    .form-actions
      .btn-group
        = f.submit nil, class: 'btn btn-primary'
        %a{value: '', class: 'btn btn-primary  hidden',title: 'Невозможно удалить тариф используемый в других заказах!', data: {toggle: 'tooltip', animation: true, placement: 'bottom'}}
          %i{class: 'fa fa-question'}

app/views/orders/_rate_form.html.haml
- if (@order.rate == nil)
  - @order.rate = Rate.new
  
- if (@order.new_record?)
  - disabled = false
- else
  - disabled = true
  .hidden
    = link_to('#', rate_new_order_path(f.object), remote: true, id: 'link_to_rate_new')

- new_or_select = new_or_select = check_box_tag('new_or_select', 'true', true, disabled: disabled, data: { :size => 'mini', :animate => 'true', :'on-color' => 'success', :'off-color' => 'warning', :'on-text' => 'Создать', :'off-text' => 'Выбрать', :'label-text' => 'Тариф'} )
= f.fields_for(:rate) do |r|
  .row
    .panel.panel-success
      .panel-heading
        - if (@order.rate == nil or @order.new_record?)
          = t('buttons.new.rate')
          %span.toright
            = new_or_select
        - else
          = r.object.name
          %br
            = check_box_tag('change', 'false', false, data: { :size => 'mini', :animate => 'true', :'on-color' => 'default', :'off-color' => 'warning', :'label-text' => 'Сменить' } )
            = new_or_select
            = check_box_tag('remove', 'false', false, data: { :size => 'mini', :animate => 'true', :'on-color' => 'default', :'off-color' => 'danger', :'label-text' => 'удалить' } )
            = f.hidden_field(:remove_rate, {id: 'remove', value: false})
            = f.hidden_field(:remove_rate_id, {value: r.object.id})
            = f.hidden_field(:rate_relation_count, {id: 'relation_count', value: r.object.orders.size})
      .panel-body#nested_attributes{:data => {:'content-select' => "#{render('rate_select', f: f)}"}}
        .from-group.row
          .col-md-6
            = r.label :name
          .col-md-6
            = r.text_field :name, class: 'form-control'
        = r.error_messages_for(:name, class: "bg-danger")
        .from-group.row
          .col-md-6
            = r.label :times_of_day
          .col-md-6
            = r.select(:times_of_day, [['ночь'], ['день']]  , {}, {:class => 'form-control'})
        = r.error_messages_for(:times_of_day, class: "bg-danger")
        .from-group.row
          .col-md-6
            = r.label :how_far
          .col-md-6 
            = r.select(:how_far, [['В пределах МКАД'], ['За МКАД'], ['Подмосковье']] , {}, {:class => 'form-control'})
        = r.error_messages_for(:how_far, class: "bg-danger")
        .from-group.row
          .col-md-6
            = r.label :PPK
          .col-md-6
            = r.text_field :PPK, class: 'form-control'
        = r.error_messages_for(:PPK, class: "bg-danger")
        = r.hidden_field(:id)

app/views/orders/_rate_select.html.haml
.panel.panel-success
  .panel-heading
    = t('app.rates.slct-button')
  .panel-body
    .form-group.row
      - if (@order.rate.id != nil)
        - rate_id = f.object.rate.id
      - else
        - rate_id = 0
      .col-md-6
        = f.label :rate
      .col-md-6
        = select(:order, :rate_id, Rate.all.where("id != ?", rate_id).collect {|p| [p.name, p.id ]}, { include_blank: true }, class: 'form-control')
    = f.error_messages_for(:rate_id)

app/views/orders/edit.html.haml
=breadcrumb_tag do
  %li
    = link_to t('app.administration'), root_path
  %li
    =link_to t('app.orders.index'), orders_path
  %li.active
    =t('app.orders.once') + ' №' + @order.id.to_s
%br
%br
= render 'form'

app/views/orders/index.html.haml
=breadcrumb_tag do
  %li
    = link_to t('app.administration'), root_path
  %li.active
    = t('app.orders.index')

.page-header
  %h1= t('headers.orders.index')

.table-responsive
  %table.table.table-hover.table-striped
    %caption
      = link_to new_order_path, class: 'btn btn-success' do
        = fa_icon :plus
        = t('buttons.new.order')  
    %thead
      %tr
        %th
        %th= Order.human_attribute_name(:date)
        %th= Order.human_attribute_name(:time)
        %th= Order.human_attribute_name(:from_adress)
        %th= Order.human_attribute_name(:to_adress)
        %th= Order.human_attribute_name(:passangers_count)
        %th= Order.human_attribute_name(:lenght_of_the_route)
        %th= Order.human_attribute_name(:driver)
        %th= Order.human_attribute_name(:rate)
        %th
    %tbody
      - @orders.each do |order|
        %tr
          %td
            = link_to order, class: 'btn btn-success' do
              = fa_icon :eye
          %td.center= order.date
          %td.center= order.time.strftime("%H:%M")
          %td.center= order.from_adress
          %td.center= order.to_adress
          %td.center= order.passangers_count
          %td.center= order.lenght_of_the_route
          %td.center= (order.driver.fn + ' ' + order.driver.sn + ' ' + order.driver.ln)
          - if order.rate_id != nil
            %td.center= order.rate.name
          - else
            %td.center Nil
          %td.right
            = link_to edit_order_path(order), class: 'btn btn-info' do
              = fa_icon :edit
              = t('buttons.edit')
            = link_to order, :method => :delete, 
            :data => { :confirm => t('buttons.confirm.order') }, 
            class: 'btn btn-danger' do
              = fa_icon :times
              = t('buttons.destroy')

app/views/orders/new.html.haml
=breadcrumb_tag do
  %li
    = link_to t('app.administration'), root_path
  %li
    = link_to t('app.orders.index'), orders_path
  %li
    = t('app.orders.new-button')
%br
%br
= render 'form'

app/views/orders/search.html.haml
=breadcrumb_tag do
  %li
    = link_to t('app.administration'), root_path
  %li
    = link_to t('app.orders.index'), orders_path
  %li
    = t('headers.orders.search')

%br
%br

= form_tag search_orders_path(), method: :get do
  .row
    .col-md-6
      .panel.panel-default
        .panel-heading
          = t('search.byorder')
        .panel-body
          .form-group
            .row
              .col-md-4
                = Order.human_attribute_name(:time)
              .col-md-8
                .row
                  .col-md-6
                    .input-group.date.timepicker
                      %span.input-group-addon
                        %span.glyphicon.glyphicon-calendar
                      = text_field_tag 'search[time_from]', params['search']['time_from'], class: 'form-control', placeholder: t('search.from')
                  .col-md-6
                    .input-group.date.timepicker
                      = text_field_tag 'search[time_to]', params['search']['time_to'], class: 'form-control', placeholder: t('search.to')
                      %span.input-group-addon
                        %span.glyphicon.glyphicon-calendar
          .form-group
            .row
              .col-md-4
                = Order.human_attribute_name(:date)
              .col-md-8
                .row
                  .col-md-6
                    .input-group.date.datepicker
                      %span.input-group-addon
                        %span.glyphicon.glyphicon-calendar
                      = text_field_tag 'search[date_from]', params['search']['date_from'], class: 'form-control', placeholder: t('search.from')
                  .col-md-6
                    .input-group.date.datepicker
                      = text_field_tag 'search[date_to]', params['search']['date_to'], class: 'form-control', placeholder: t('search.to')
                      %span.input-group-addon
                        %span.glyphicon.glyphicon-calendar
          .form-group
            .row
              .col-md-4
                = Order.human_attribute_name(:passangers_count)
              .col-md-8
                = text_field_tag 'search[passangers_count]', params['search']['passangers_count'], class: 'form-control'
          .form-group
            .row
              .col-md-4
                = Order.human_attribute_name(:lenght_of_the_route)
              .col-md-8
                = text_field_tag('search[lenght_of_the_route]', params['search']['lenght_of_the_route'], class: 'form-control', data: {:'slider-min' => '1', :'slider-max' => '150', :'slider-step' => '1', :'slider-value' => '[0, 150]'})
          .form-group
            .row
              .col-md-4
                = Order.human_attribute_name(:from_adress)
              .col-md-8
                = text_field_tag 'search[from_adress]', params['search']['from_adress'], class: 'form-control'
          .form-group
            .row
              .col-md-4
                = Order.human_attribute_name(:to_adress)
              .col-md-8
                = text_field_tag 'search[to_adress]', params['search']['to_adress'], class: 'form-control'
    .col-md-6
      .panel.panel-default
        .panel-heading
          = t('search.byrate')
        .panel-body
          .form-group
            .row
              .col-md-4
                = Rate.human_attribute_name(:name)
              .col-md-8
                = select_tag 'search[rate_name]', options_for_select((Rate.all.map{|x| [x.name, x.name]}.sort), @s_rate_name), {include_blank: true, class: 'form-control'}
          .form-group
            .row
              .col-md-4
                = Rate.human_attribute_name(:times_of_day)
              .col-md-8
                = select_tag 'search[times_of_day]', options_for_select((Rate.all.map{|x| [x.times_of_day, x.times_of_day]}.uniq.sort), @s_rate_times_of_day), {include_blank: true, class: 'form-control'}
          .form-group
            .row
              .col-md-4
                = Rate.human_attribute_name(:how_far)
              .col-md-8
                = select_tag 'search[how_far]', options_for_select((Rate.all.map{|x| [x.how_far, x.how_far]}.uniq.sort), @s_rate_how_far),{include_blank: true, class: 'form-control'}
          .form-group
            .row
              .col-md-4
                = Rate.human_attribute_name(:PPK)
              .col-md-8
                = text_field_tag('search[PPK]', params['search']['PPK'], class: 'form-control', data: {'slider-min' => '75', 'slider-max' => '750', 'slider-step' => '5', 'slider-value' => '[75, 750]'})
  .row
    .col-md-6
      .panel.panel-default
        .panel-heading
          = t('search.byauto')
        .panel-body
          .form-group
            .row
              .col-md-4
                = Auto.human_attribute_name(:model)
              .col-md-8
                = select_tag 'search[auto_model]', options_for_select((Auto.all.map{|x| [x.model, x.model]}.uniq.sort), @s_auto_model),{include_blank: true, class: 'form-control'}
          .form-group
            .row
              .col-md-4
                = Auto.human_attribute_name(:class)
              .col-md-8
                = select_tag 'search[auto_class]', options_for_select((Auto.all.map{|x| [x.myclass, x.myclass]}.uniq.sort), @s_auto_class),{include_blank: true, class: 'form-control'}
          .form-group
            .row
              .col-md-4
                = Auto.human_attribute_name(:number)
              .col-md-8
                = text_field_tag 'search[auto_number]', params['search']['state_number'], {include_blank: true, class: 'form-control'}
          .form-group
            .row
              .col-md-4
                = Auto.human_attribute_name(:color)
              .col-md-8
                = select_tag 'search[auto_color]', options_for_select((Auto.all.map{|x| [x.color, x.color]}.uniq.sort), @s_auto_color), {include_blank: true, class: 'form-control'}
          .form-group
            .row
              .col-md-4
                = Auto.human_attribute_name(:year)
              .col-md-8
                = text_field_tag 'search[year]', params['search']['year'], {include_blank: true, class: 'form-control'}
    .col-md-6
      .panel.panel-default
        .panel-heading
          = t('search.bydriver')
        .panel-body
          .form-group
            .row
              .col-md-4
                = Driver.human_attribute_name(:fn)
              .col-md-8
                = text_field_tag 'search[driver_fn]', params['search']['driver_fn'], class: 'form-control'
          .form-group
            .row
              .col-md-4
                = Driver.human_attribute_name(:sn)
              .col-md-8
                = text_field_tag 'search[driver_sn]', params['search']['driver_sn'], class: 'form-control'
          .form-group
            .row
              .col-md-4
                = Driver.human_attribute_name(:ln)
              .col-md-8
                = text_field_tag 'search[driver_ln]', params['search']['driver_ln'], class: 'form-control'
          .form-group
            .row
              .col-md-4
                = Driver.human_attribute_name(:birthdate)
              .col-md-8
                .input-group.date.datepicker
                  = text_field_tag 'search[driver_birthdate]', params['search']['driver_birthdate'], class: 'form-control'
                  %span.input-group-addon
                    %span.glyphicon.glyphicon-calendar
          .form-group
            .row
              .col-md-4
                = Driver.human_attribute_name(:TIN)
              .col-md-8
                = text_field_tag 'search[driver_TIN]', params['search']['driver_TIN'], class: 'form-control'
          .form-group
            .row
              .col-md-4
                = Driver.human_attribute_name(:passport)
              .col-md-8
                = text_field_tag 'search[driver_passport]', params['search']['driver_passport'], class: 'form-control'

  .actions
    = submit_tag t('buttons.search'), class: 'btn btn-primary', id: 'search-button'



- if @orders.size > 0
  .page-header
    %h1= t('search.found') + ": " + @orders.size.to_s
  
  %table.table-responsive
    %tr
    - @orders.each do |order|
      %td
        .panel.panel-success
          .panel-heading
            = t('app.orders.once') + ' № ' + order.id.to_s
          .panel-body
            %table.table.table-striped.table-condensed.table-hover
              %tr
                %td
                  = Order.human_attribute_name(:time)
                %td
                  = order.time.strftime("%H:%M")
              %tr
                %td
                  = Order.human_attribute_name(:from_adress)
                %td
                  = order.from_adress
              %tr
                %td
                  = Order.human_attribute_name(:to_adress)
                %td
                  = order.to_adress
              %tr
                %td
                  = Order.human_attribute_name(:passangers_count)
                %td
                  = order.passangers_count
              %tr
                %td
                  = Order.human_attribute_name(:lenght_of_the_route)
                %td
                  = order.lenght_of_the_route
            %table.table.table-striped.table-condensed.table-hover
              %thead
                %tr
                  %th{colspan: "2"}
                    = Driver.human_attribute_name(:auto)
              %tbody
                %tr
                  %td
                    = Auto.human_attribute_name(:model)
                  %td
                    = "#{order.driver.auto.model}"
                %tr
                  %td
                    = Auto.human_attribute_name(:number)
                  %td
                    = "#{order.driver.auto.number}"
                %tr
                  %td
                    = Auto.human_attribute_name(:class)
                  %td
                    = "#{order.driver.auto.myclass}"
            %table.table.table-striped.table-condensed.table-hover
              %thead
                %tr
                  %th{colspan: "2"}
                    = Order.human_attribute_name(:rate)
              %tbody
                %tr
                  %td
                    = Rate.human_attribute_name(:name)
                  %td
                    = "#{order.rate.name}"
                %tr
                  %td
                    = Rate.human_attribute_name(:times_of_day)
                  %td
                    = "#{order.rate.times_of_day}"
                %tr
                  %td
                    = Rate.human_attribute_name(:how_far)
                  %td
                    = "#{order.rate.how_far}"
                %tr
                  %td
                    = Rate.human_attribute_name(:PPK)
                  %td
                    = "#{order.rate.PPK} руб./км}"
            %table.table.table-striped.table-condensed.table-hover
              %thead
                %tr
                  %th{colspan: "2"}
                    = Order.human_attribute_name(:driver)
              %tbody
                %tr
                  %td
                    = Driver.human_attribute_name(:fn)
                  %td
                    = "#{order.driver.fn}"
                %tr
                  %td
                    = Driver.human_attribute_name(:sn)
                  %td
                    = "#{order.driver.sn}"
                %tr
                  %td
                    = Driver.human_attribute_name(:ln)
                  %td
                    = "#{order.driver.ln}"
                %tr
                  %td
                    = Driver.human_attribute_name(:birthdate)
                  %td
                    = "#{order.driver.birthdate}"
                %tr
                  %td
                    = Driver.human_attribute_name(:TIN)
                  %td
                    = "#{order.driver.TIN}"
                %tr
                  %td
                    = Driver.human_attribute_name(:passport)
                  %td
                    = "#{order.driver.passport}"

app/views/orders/show.html.haml
=breadcrumb_tag do
  %li
    = link_to t('app.administration'), root_path
  %li
    = link_to t('app.orders.index'), orders_path
  %li.active
    = 'Заказ №' + @order.id.to_s
%br
%br
%p
  %b= Order.human_attribute_name(:date) + ':'
  = @order.date
%p
  %b= Order.human_attribute_name(:time) + ':'
  = @order.time.strftime("%H:%M")
%p
  %b= Order.human_attribute_name(:from_adress) + ':'
  = @order.from_adress
%p
  %b= Order.human_attribute_name(:to_adress) + ':'
  = @order.to_adress
%p
  %b= Order.human_attribute_name(:passangers_count) + ':'
  = @order.passangers_count
%p
  %b= Order.human_attribute_name(:lenght_of_the_route) + ':'
  = @order.lenght_of_the_route
%p
  %b= Order.human_attribute_name(:driver) + ':'
  = @order.driver.fn + ' ' + @order.driver.sn + ' ' + @order.driver.ln
%p
  - if @order.rate_id != nil
    %b= Order.human_attribute_name(:rate) + ':'
    = @order.rate.name
  - else
    %b= Order.human_attribute_name(:rate) + ':'
    Nil

= link_to edit_order_path(@order), class: 'btn btn-info' do
  = fa_icon :edit
  = t('buttons.edit')