config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    collection do
      get :search
    end
    member do
      get :rate_new
    end
  end
  resources :rates
  resources :drivers do
    member do
      get :auto_new
    end
  end
  resources :autos
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  
  attr_accessor :remove_auto
  attr_accessor :remove_auto_id
  
  after_update :destroy_auto
  
	belongs_to :auto, inverse_of: :drivers
	accepts_nested_attributes_for :auto, allow_destroy: true
  
	validates :fn, presence: true
	validates :sn, presence: true
	validates :ln, presence: true
	validates :birthdate, presence: true
	validates :TIN, length: {is: 10}, numericality: { only_integer: true, allow_nil: false }
	validates :passport, length: {is: 10}, numericality: { only_integer: true, allow_nil: false }
  validates :auto, presence: true
  
  protected
  
  def destroy_auto
    if (remove_auto == "true")
      relationship = Auto.find(remove_auto_id).drivers.select{|s| s.id != self.id}
      if (relationship.empty? and (auto_id.to_i != remove_auto_id.to_i))
        Auto.delete(remove_auto_id)
      end  
    end
  end
  
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]
  before_action -> {check_permissions('admin', 'operator')}, except: [:show, :index]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end
  
  def auto_new
    respond_to do |format|
      format.js do
        @driver = Driver.find(params[:id])
        @driver.auto = Auto.new
      end
    end
  end
  
  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: t('app.drivers.create.success') }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: t('app.drivers.update.success') }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: t('app.drivers.destroy.success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:fn, :sn, :ln, :birthdate, :TIN, :passport, :auto_id, :remove_auto, :remove_auto_id,
      auto_attributes: [:id, :model, :myclass, :number, :color, :year, :_destroy]
        )
    end
end

app/helpers/drivers_helper.rb
module DriversHelper
end 

app/views/drivers/_auto_form.html.haml
- if (@driver.auto == nil)
  - @driver.auto = Auto.new
  
- if (@driver.new_record?)
  - disabled = false
- else
  - disabled = true
  .hidden
    = link_to('#', auto_new_driver_path(f.object), remote: true, id: 'link_to_auto_new')
  
- new_or_select = new_or_select = check_box_tag('new_or_select', 'true', true, disabled: disabled, data: { :size => 'mini', :animate => 'true', :'on-color' => 'success', :'off-color' => 'warning', :'on-text' => 'Создать', :'off-text' => 'Выбрать', :'label-text' => 'Автомобиль'} )
= f.fields_for(:auto) do |a|
  .row
    .panel.panel-success
      .panel-heading
        - if (@driver.auto == nil or @driver.new_record?)
          = t('buttons.new.auto')
          %span.toright
            = new_or_select
        - else
          = f.object.auto.model + ' ' + f.object.auto.number
          %br
            = check_box_tag('change', 'false', false, data: { :size => 'mini', :animate => 'true', :'on-color' => 'default', :'off-color' => 'warning', :'label-text' => 'Сменить' } )
            = new_or_select
            = check_box_tag('remove', 'false', false, data: { :size => 'mini', :animate => 'true', :'on-color' => 'default', :'off-color' => 'danger', :'label-text' => 'удалить' } )
            = f.hidden_field(:remove_auto, {id: 'remove', value: false})
            = f.hidden_field(:remove_auto_id, {value: a.object.id})
            = f.hidden_field(:auto_relation_count, {id: 'relation_count', value: a.object.drivers.size})
      .panel-body#nested_attributes{:data => {:'content-select' => "#{render('auto_select', f: f)}"}}
        .from-group.row
          .col-md-2
            = a.label :model
          .col-md-6
            = a.text_field :model, class: 'form-control'
            = a.error_messages_for(:model)
        .from-group.row
          .col-md-2
            = a.label :class
          .col-md-6
            = a.select(:myclass, [['эконом'], ['бизнес']] , {}, {:class => 'form-control'})
            = a.error_messages_for(:myclass)
        .from-group.row
          .col-md-2
            = a.label :number
          .col-md-6
            = a.text_field :number, class: 'form-control'
            = a.error_messages_for(:number)
        .from-group.row
          .col-md-2
            = a.label :color
          .col-md-6
            = a.text_field :color, class: 'form-control'
            = a.error_messages_for(:color)
        .from-group.row
          .col-md-2
            = a.label :year
          .col-md-6
            .input-group.date.yearpicker
              = a.text_field :year, class: 'form-control', value: a.object.year
              %span.input-group-addon
                %span.glyphicon.glyphicon-calendar
        = a.error_messages_for(:year)
        = a.hidden_field(:id)

app/views/drivers/_auto_select.html.haml
.panel.panel-success
  .panel-heading
    = t('app.autos.slct-button')
  .panel-body
    .form-group.row
      - if (@driver.auto.id != nil)
        - auto_id = f.object.auto.id
      - else
        - auto_id = 0
      .col-md-4
        = f.label :auto
      .col-md-8
        = select(:driver, :auto_id, Auto.all.where("id != ?", auto_id).collect {|p| [ (p.model + ' - ' + p.number), p.id ] }, { include_blank: true }, class: 'form-control')
    = f.error_messages_for(:auto_id)

app/views/drivers/_form.html.haml
= form_for @driver do |f|
  - if @driver.errors.any? && @current_role_user.is_admin?
    #error_explanation
      %h2= "#{pluralize(@driver.errors.count, "error")} prohibited this driver from being saved:"
      %ul
        - @driver.errors.full_messages.each do |msg|
          %li= msg
  .row
    .col-md-6
      .form-group
        .row
          .col-md-4
            = f.label :fn
          .col-md-8
            = f.text_field :fn, class: 'form-control'
      = f.error_messages_for(:fn)
      .form-group
        .row
          .col-md-4
            = f.label :sn
          .col-md-8
            = f.text_field :sn, class: 'form-control'
      = f.error_messages_for(:sn)
      .form-group
        .row
          .col-md-4
            = f.label :ln
          .col-md-8
            = f.text_field :ln, class: 'form-control'
      = f.error_messages_for(:sn)
      .form-group
        .row
          .col-md-4
            = f.label :birthdate
          .col-md-8
            .input-group.date.datepicker
              = f.text_field :birthdate, value: lnil(f.object.birthdate), class: 'form-control'
              %span.input-group-addon
                %span.glyphicon.glyphicon-calendar
      = f.error_messages_for(:birthdate)
      .form-group
        .row
          .col-md-4
            = f.label :TIN
          .col-md-8
            = f.text_field :TIN, class: 'form-control'
      = f.error_messages_for(:TIN)
      .form-group
        .row
          .col-md-4
            = f.label :passport
          .col-md-8
            = f.text_field :passport, class: 'form-control'
      = f.error_messages_for(:passport)
    - if @current_role_user.present? and @current_role_user.is_admin?
      .col-md-6
        = render('auto_form', f: f)
  .col-md-6.col-md-offset-3
    .form-actions
      .btn-group
        = f.submit nil, class: 'btn btn-primary'
        %a{value: '', class: 'btn btn-primary  hidden',title: 'Невозможно удалить автомобиль принадлежащий другим водителям!', data: {toggle: 'tooltip', animation: true, placement: 'bottom'}}
          %i{class: 'fa fa-question'}

app/views/drivers/edit.html.haml
=breadcrumb_tag do
  %li
    = link_to t('app.administration'), root_path
  %li
    = link_to t('app.drivers.index'), drivers_path
  %li.active
    = @driver.fn + ' ' + @driver.sn + ' ' + @driver.ln
%br
%br
= render 'form'

app/views/drivers/index.html.haml
=breadcrumb_tag do
  %li
    Администрирование
  %li.active
    =t('app.drivers.index')

.page-header
  %h1= t('headers.drivers.index')
  
.table-responsive
  %table.table.table-hover.table-striped
    %caption
      = link_to new_driver_path, class: 'btn btn-success' do
        = fa_icon :plus
        = t('buttons.new.driver')  
    %thead
      %tr
        %th
        %th= Driver.human_attribute_name(:fn)
        %th= Driver.human_attribute_name(:sn)
        %th= Driver.human_attribute_name(:ln)
        %th= Driver.human_attribute_name(:birthdate)
        %th= Driver.human_attribute_name(:TIN)
        %th= Driver.human_attribute_name(:passport)
        %th= Driver.human_attribute_name(:auto)
        %th
    %tbody
      - @drivers.each do |driver|
        %tr
          %td.left 
            = link_to driver, class: 'btn btn-success' do
              = fa_icon :eye
          %td.center= driver.fn
          %td.center= driver.sn
          %td.center= driver.ln
          %td.center= driver.birthdate
          %td.center= driver.TIN
          %td.center= driver.passport
          - if driver.auto_id != nil
            %td.center= driver.auto.model + ' - ' + driver.auto.number
          - else
            %td.center null
          %td.right
            = link_to edit_driver_path(driver), class: 'btn btn-info' do
              = fa_icon :edit
              = t('buttons.edit')
            = link_to driver, :method => :delete, 
            :data => { :confirm => t('buttons.confirm.driver') }, 
            class: 'btn btn-danger' do
              = fa_icon :times
              = t('buttons.destroy')

app/views/drivers/new.html.haml
=breadcrumb_tag do
  %li
    = link_to t('app.administration'), root_path
  %li
    = link_to t('app.drivers.index'), drivers_path
  %li.active
    = 'Новый водитель'
%br
%br
= render 'form'

app/views/drivers/show.html.haml
=breadcrumb_tag do
  %li
    = link_to t('app.administration'), root_path
  %li
    = link_to t('app.drivers.index'), drivers_path
  %li.active
    = @driver.fn + ' ' + @driver.sn + ' ' + @driver.ln
%br
%br

%p
  %b= Driver.human_attribute_name(:fn) + ':'
  = @driver.fn
%p
  %b= Driver.human_attribute_name(:sn) + ':'
  = @driver.sn
%p
  %b= Driver.human_attribute_name(:ln) + ':'
  = @driver.ln
%p
  %b= Driver.human_attribute_name(:birthdate) + ':'
  = @driver.birthdate
%p
  %b= Driver.human_attribute_name(:TIN) + ':'
  = @driver.TIN
%p
  %b= Driver.human_attribute_name(:passport) + ':'
  = @driver.passport
%p
  - if @driver.auto_id != nil
    %b= Driver.human_attribute_name(:auto) + ':'
    = @driver.auto.model + ' - ' + @driver.auto.number
  - else
    %b= Driver.human_attribute_name(:auto) + ':'
    NULL
= link_to edit_driver_path(@driver), class: 'btn btn-info' do
  = fa_icon :edit
  = t('buttons.edit')